version: "3"

services:
  jupyterhub:
    build:
      context: .
      args:
        BASE: quay.io/jupyterhub/jupyterhub:4.0.2
    ports:
      - "8000:8000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
    environment:
      - "JUPYTERHUB_CRYPT_KEY=hAi4paBnF_dwzbM-RmddVA45rohpeOIK4NBkBOE9e38="
